// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zigbeealliance/distributedcomplianceledger/model/model.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Model struct {
	Vid                                        int32  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Pid                                        int32  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	DeviceTypeId                               int32  `protobuf:"varint,3,opt,name=deviceTypeId,proto3" json:"deviceTypeId,omitempty"`
	ProductName                                string `protobuf:"bytes,4,opt,name=productName,proto3" json:"productName,omitempty"`
	ProductLabel                               string `protobuf:"bytes,5,opt,name=productLabel,proto3" json:"productLabel,omitempty"`
	PartNumber                                 string `protobuf:"bytes,6,opt,name=partNumber,proto3" json:"partNumber,omitempty"`
	CommissioningCustomFlow                    int32  `protobuf:"varint,7,opt,name=commissioningCustomFlow,proto3" json:"commissioningCustomFlow,omitempty"`
	CommissioningCustomFlowUrl                 string `protobuf:"bytes,8,opt,name=commissioningCustomFlowUrl,proto3" json:"commissioningCustomFlowUrl,omitempty"`
	CommissioningModeInitialStepsHint          uint32 `protobuf:"varint,9,opt,name=commissioningModeInitialStepsHint,proto3" json:"commissioningModeInitialStepsHint,omitempty"`
	CommissioningModeInitialStepsInstruction   string `protobuf:"bytes,10,opt,name=commissioningModeInitialStepsInstruction,proto3" json:"commissioningModeInitialStepsInstruction,omitempty"`
	CommissioningModeSecondaryStepsHint        uint32 `protobuf:"varint,11,opt,name=commissioningModeSecondaryStepsHint,proto3" json:"commissioningModeSecondaryStepsHint,omitempty"`
	CommissioningModeSecondaryStepsInstruction string `protobuf:"bytes,12,opt,name=commissioningModeSecondaryStepsInstruction,proto3" json:"commissioningModeSecondaryStepsInstruction,omitempty"`
	UserManualUrl                              string `protobuf:"bytes,13,opt,name=userManualUrl,proto3" json:"userManualUrl,omitempty"`
	SupportUrl                                 string `protobuf:"bytes,14,opt,name=supportUrl,proto3" json:"supportUrl,omitempty"`
	ProductUrl                                 string `protobuf:"bytes,15,opt,name=productUrl,proto3" json:"productUrl,omitempty"`
	LsfUrl                                     string `protobuf:"bytes,16,opt,name=lsfUrl,proto3" json:"lsfUrl,omitempty"`
	LsfRevision                                int32  `protobuf:"varint,17,opt,name=lsfRevision,proto3" json:"lsfRevision,omitempty"`
	Creator                                    string `protobuf:"bytes,18,opt,name=creator,proto3" json:"creator,omitempty"`
	SchemaVersion                              uint32 `protobuf:"varint,19,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	EnhancedSetupFlowOptions                   int32  `protobuf:"varint,20,opt,name=enhancedSetupFlowOptions,proto3" json:"enhancedSetupFlowOptions,omitempty" validate:"omitempty,gte=0,lte=65535"`
	EnhancedSetupFlowTCUrl                     string `protobuf:"bytes,21,opt,name=enhancedSetupFlowTCUrl,proto3" json:"enhancedSetupFlowTCUrl,omitempty" validate:"required_if_bit_0_set=EnhancedSetupFlowOptions,omitempty,url,startswith=https:,max=256"`
	EnhancedSetupFlowTCRevision                int32  `protobuf:"varint,22,opt,name=enhancedSetupFlowTCRevision,proto3" json:"enhancedSetupFlowTCRevision,omitempty" validate:"required_if_bit_0_set=EnhancedSetupFlowOptions,gte=0,lte=65535"`
	EnhancedSetupFlowTCDigest                  string `protobuf:"bytes,23,opt,name=enhancedSetupFlowTCDigest,proto3" json:"enhancedSetupFlowTCDigest,omitempty" validate:"required_if_bit_0_set=EnhancedSetupFlowOptions,omitempty,max=128"`
	EnhancedSetupFlowTCFileSize                uint32 `protobuf:"varint,24,opt,name=enhancedSetupFlowTCFileSize,proto3" json:"enhancedSetupFlowTCFileSize,omitempty" validate:"required_with=EnhancedSetupFlowTCUrl"`
	EnhancedSetupFlowMaintenanceUrl            string `protobuf:"bytes,25,opt,name=enhancedSetupFlowMaintenanceUrl,proto3" json:"enhancedSetupFlowMaintenanceUrl,omitempty" validate:"required_if_bit_0_set=EnhancedSetupFlowOptions,omitempty,url,startswith=https:,max=256"`
	DiscoveryCapabilitiesBitmask               uint32 `protobuf:"varint,26,opt,name=discoveryCapabilitiesBitmask,proto3" json:"discoveryCapabilitiesBitmask,omitempty" validate:"gte=0,lte=14"`
	CommissioningFallbackUrl                   string `protobuf:"bytes,27,opt,name=commissioningFallbackUrl,proto3" json:"commissioningFallbackUrl,omitempty" validate:"omitempty,url,startsnotwith=http:,max=256"`
	IcdUserActiveModeTriggerHint               uint32 `protobuf:"varint,28,opt,name=icdUserActiveModeTriggerHint,proto3" json:"icdUserActiveModeTriggerHint,omitempty"`
	IcdUserActiveModeTriggerInstruction        string `protobuf:"bytes,29,opt,name=icdUserActiveModeTriggerInstruction,proto3" json:"icdUserActiveModeTriggerInstruction,omitempty"`
	FactoryResetStepsHint                      uint32 `protobuf:"varint,30,opt,name=factoryResetStepsHint,proto3" json:"factoryResetStepsHint,omitempty"`
	FactoryResetStepsInstruction               string `protobuf:"bytes,31,opt,name=factoryResetStepsInstruction,proto3" json:"factoryResetStepsInstruction,omitempty"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_363bb1b07b19a129, []int{0}
}
func (m *Model) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Model.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return m.Size()
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetVid() int32 {
	if m != nil {
		return m.Vid
	}
	return 0
}

func (m *Model) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Model) GetDeviceTypeId() int32 {
	if m != nil {
		return m.DeviceTypeId
	}
	return 0
}

func (m *Model) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Model) GetProductLabel() string {
	if m != nil {
		return m.ProductLabel
	}
	return ""
}

func (m *Model) GetPartNumber() string {
	if m != nil {
		return m.PartNumber
	}
	return ""
}

func (m *Model) GetCommissioningCustomFlow() int32 {
	if m != nil {
		return m.CommissioningCustomFlow
	}
	return 0
}

func (m *Model) GetCommissioningCustomFlowUrl() string {
	if m != nil {
		return m.CommissioningCustomFlowUrl
	}
	return ""
}

func (m *Model) GetCommissioningModeInitialStepsHint() uint32 {
	if m != nil {
		return m.CommissioningModeInitialStepsHint
	}
	return 0
}

func (m *Model) GetCommissioningModeInitialStepsInstruction() string {
	if m != nil {
		return m.CommissioningModeInitialStepsInstruction
	}
	return ""
}

func (m *Model) GetCommissioningModeSecondaryStepsHint() uint32 {
	if m != nil {
		return m.CommissioningModeSecondaryStepsHint
	}
	return 0
}

func (m *Model) GetCommissioningModeSecondaryStepsInstruction() string {
	if m != nil {
		return m.CommissioningModeSecondaryStepsInstruction
	}
	return ""
}

func (m *Model) GetUserManualUrl() string {
	if m != nil {
		return m.UserManualUrl
	}
	return ""
}

func (m *Model) GetSupportUrl() string {
	if m != nil {
		return m.SupportUrl
	}
	return ""
}

func (m *Model) GetProductUrl() string {
	if m != nil {
		return m.ProductUrl
	}
	return ""
}

func (m *Model) GetLsfUrl() string {
	if m != nil {
		return m.LsfUrl
	}
	return ""
}

func (m *Model) GetLsfRevision() int32 {
	if m != nil {
		return m.LsfRevision
	}
	return 0
}

func (m *Model) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Model) GetSchemaVersion() uint32 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

func (m *Model) GetEnhancedSetupFlowOptions() int32 {
	if m != nil {
		return m.EnhancedSetupFlowOptions
	}
	return 0
}

func (m *Model) GetEnhancedSetupFlowTCUrl() string {
	if m != nil {
		return m.EnhancedSetupFlowTCUrl
	}
	return ""
}

func (m *Model) GetEnhancedSetupFlowTCRevision() int32 {
	if m != nil {
		return m.EnhancedSetupFlowTCRevision
	}
	return 0
}

func (m *Model) GetEnhancedSetupFlowTCDigest() string {
	if m != nil {
		return m.EnhancedSetupFlowTCDigest
	}
	return ""
}

func (m *Model) GetEnhancedSetupFlowTCFileSize() uint32 {
	if m != nil {
		return m.EnhancedSetupFlowTCFileSize
	}
	return 0
}

func (m *Model) GetEnhancedSetupFlowMaintenanceUrl() string {
	if m != nil {
		return m.EnhancedSetupFlowMaintenanceUrl
	}
	return ""
}

func (m *Model) GetDiscoveryCapabilitiesBitmask() uint32 {
	if m != nil {
		return m.DiscoveryCapabilitiesBitmask
	}
	return 0
}

func (m *Model) GetCommissioningFallbackUrl() string {
	if m != nil {
		return m.CommissioningFallbackUrl
	}
	return ""
}

func (m *Model) GetIcdUserActiveModeTriggerHint() uint32 {
	if m != nil {
		return m.IcdUserActiveModeTriggerHint
	}
	return 0
}

func (m *Model) GetIcdUserActiveModeTriggerInstruction() string {
	if m != nil {
		return m.IcdUserActiveModeTriggerInstruction
	}
	return ""
}

func (m *Model) GetFactoryResetStepsHint() uint32 {
	if m != nil {
		return m.FactoryResetStepsHint
	}
	return 0
}

func (m *Model) GetFactoryResetStepsInstruction() string {
	if m != nil {
		return m.FactoryResetStepsInstruction
	}
	return ""
}

func init() {
	proto.RegisterType((*Model)(nil), "zigbeealliance.distributedcomplianceledger.model.Model")
}

func init() {
	proto.RegisterFile("zigbeealliance/distributedcomplianceledger/model/model.proto", fileDescriptor_363bb1b07b19a129)
}

var fileDescriptor_363bb1b07b19a129 = []byte{
	// 950 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xee, 0x52, 0x92, 0xd2, 0x69, 0x03, 0xed, 0x90, 0x26, 0x93, 0x0f, 0xec, 0x60, 0x7a, 0xb0,
	0x90, 0x13, 0xa7, 0xf9, 0xa8, 0xa2, 0x0a, 0x23, 0xd5, 0xa1, 0x11, 0x11, 0x4d, 0x8b, 0xd6, 0x29,
	0x87, 0x1e, 0x30, 0xe3, 0xdd, 0x37, 0xeb, 0x51, 0x77, 0x77, 0x96, 0x99, 0x77, 0xdd, 0xba, 0xff,
	0x01, 0xc1, 0x1f, 0xe0, 0x37, 0x70, 0xe1, 0xca, 0x9d, 0x63, 0xc5, 0x89, 0x93, 0x85, 0x92, 0x7f,
	0xe0, 0x5f, 0x80, 0x66, 0xd6, 0x8d, 0x6d, 0xf9, 0x23, 0x01, 0x21, 0x2e, 0x96, 0xf7, 0x79, 0x9e,
	0xf7, 0xdd, 0x67, 0x9e, 0x7d, 0x77, 0x76, 0xc8, 0x67, 0xaf, 0x45, 0xd0, 0x00, 0xe0, 0x61, 0x28,
	0x78, 0xec, 0x41, 0xd9, 0x17, 0x1a, 0x95, 0x68, 0xa4, 0x08, 0xbe, 0x27, 0xa3, 0x24, 0x43, 0x43,
	0xf0, 0x03, 0x50, 0xe5, 0x48, 0xfa, 0x10, 0x66, 0xbf, 0x1b, 0x89, 0x92, 0x28, 0xe9, 0xe6, 0x70,
	0xf5, 0xc6, 0x94, 0xea, 0x0d, 0x5b, 0xb7, 0xbc, 0xe4, 0x49, 0x1d, 0x49, 0x5d, 0xb7, 0xf5, 0xe5,
	0xec, 0x22, 0x6b, 0xb6, 0x3c, 0x1f, 0xc8, 0x40, 0x66, 0xb8, 0xf9, 0x97, 0xa1, 0x85, 0xdf, 0x6e,
	0x93, 0x99, 0x23, 0x53, 0x4a, 0x6f, 0x91, 0xab, 0x2d, 0xe1, 0x33, 0x67, 0xcd, 0x29, 0xce, 0xb8,
	0xe6, 0xaf, 0x41, 0x12, 0xe1, 0xb3, 0x77, 0x32, 0x24, 0x11, 0x3e, 0x2d, 0x90, 0x9b, 0x3e, 0xb4,
	0x84, 0x07, 0xc7, 0xed, 0x04, 0x0e, 0x7d, 0x76, 0xd5, 0x52, 0x43, 0x18, 0x5d, 0x23, 0x37, 0x12,
	0x25, 0xfd, 0xd4, 0xc3, 0x27, 0x3c, 0x02, 0xf6, 0xee, 0x9a, 0x53, 0xbc, 0xee, 0x0e, 0x42, 0xa6,
	0x4b, 0xef, 0xf2, 0x31, 0x6f, 0x40, 0xc8, 0x66, 0xac, 0x64, 0x08, 0xa3, 0x39, 0x42, 0x12, 0xae,
	0xf0, 0x49, 0x1a, 0x35, 0x40, 0xb1, 0x59, 0xab, 0x18, 0x40, 0xe8, 0x1e, 0x59, 0xf4, 0x64, 0x14,
	0x09, 0xad, 0x85, 0x8c, 0x45, 0x1c, 0xec, 0xa7, 0x1a, 0x65, 0x74, 0x10, 0xca, 0x97, 0xec, 0x9a,
	0x35, 0x35, 0x89, 0xa6, 0x9f, 0x93, 0xe5, 0x09, 0xd4, 0x33, 0x15, 0xb2, 0xf7, 0xec, 0x9d, 0xa6,
	0x28, 0xe8, 0x63, 0xf2, 0xf1, 0x10, 0x6b, 0xd2, 0x3b, 0x8c, 0x05, 0x0a, 0x1e, 0xd6, 0x10, 0x12,
	0xfd, 0xa5, 0x88, 0x91, 0x5d, 0x5f, 0x73, 0x8a, 0x73, 0xee, 0xc5, 0x42, 0xfa, 0x9c, 0x14, 0xa7,
	0x8a, 0x0e, 0x63, 0x8d, 0x2a, 0xf5, 0x50, 0xc8, 0x98, 0x11, 0xeb, 0xed, 0xd2, 0x7a, 0xfa, 0x35,
	0xf9, 0x64, 0x44, 0x5b, 0x03, 0x4f, 0xc6, 0x3e, 0x57, 0xed, 0xbe, 0xd7, 0x1b, 0xd6, 0xeb, 0x65,
	0xa4, 0xf4, 0x5b, 0xf2, 0xe9, 0x05, 0xb2, 0x41, 0xbf, 0x37, 0xad, 0xdf, 0x7f, 0x50, 0x41, 0xef,
	0x92, 0xb9, 0x54, 0x83, 0x3a, 0xe2, 0x71, 0xca, 0x43, 0xf3, 0x38, 0xe6, 0x6c, 0x8b, 0x61, 0xd0,
	0xcc, 0x86, 0x4e, 0x93, 0x44, 0x2a, 0x34, 0x92, 0xf7, 0xb3, 0xd9, 0xe8, 0x23, 0x76, 0x76, 0xb2,
	0x59, 0x32, 0xfc, 0x07, 0xbd, 0xd9, 0x39, 0x47, 0xe8, 0x02, 0x99, 0x0d, 0xf5, 0x89, 0xe1, 0x6e,
	0x59, 0xae, 0x77, 0x65, 0x26, 0x37, 0xd4, 0x27, 0x2e, 0xb4, 0x84, 0x31, 0xcb, 0x6e, 0xdb, 0x39,
	0x1a, 0x84, 0xe8, 0x16, 0xb9, 0xe6, 0x29, 0xe0, 0x28, 0x15, 0xa3, 0xa6, 0xb4, 0xca, 0xfe, 0xf8,
	0x75, 0x7d, 0xbe, 0xf7, 0x9a, 0x3d, 0xf4, 0x7d, 0x05, 0x5a, 0xd7, 0x50, 0x89, 0x38, 0x70, 0xdf,
	0x0a, 0xcd, 0x9a, 0xb4, 0xd7, 0x84, 0x88, 0x7f, 0x03, 0xca, 0xf6, 0xfd, 0xd0, 0xe6, 0x3d, 0x0c,
	0x52, 0x9f, 0x30, 0x88, 0x9b, 0xe6, 0x7d, 0xf6, 0x6b, 0x80, 0x69, 0x62, 0xa6, 0xed, 0x69, 0x62,
	0x42, 0xd1, 0x6c, 0xde, 0x18, 0xa9, 0x16, 0xbb, 0x9d, 0xfc, 0xdd, 0x16, 0x0f, 0x85, 0xcf, 0x11,
	0x1e, 0x14, 0x64, 0x24, 0x10, 0xa2, 0x04, 0xdb, 0xa5, 0x00, 0xa1, 0xb2, 0x59, 0x0a, 0x11, 0x2a,
	0xf7, 0x77, 0x77, 0xb7, 0x77, 0x0b, 0xee, 0xc4, 0x4e, 0xf4, 0x67, 0x87, 0x2c, 0x8c, 0x90, 0xc7,
	0xfb, 0x26, 0x8a, 0x3b, 0x76, 0x3d, 0xd0, 0xed, 0xe4, 0x79, 0xff, 0x26, 0x0a, 0xbe, 0x4f, 0x85,
	0x02, 0xbf, 0x2e, 0x4e, 0xea, 0x0d, 0x81, 0xf5, 0xcd, 0xba, 0x06, 0xac, 0x3c, 0x9a, 0xd0, 0xbe,
	0xd4, 0xf7, 0x94, 0xaa, 0xb0, 0xa4, 0x91, 0x2b, 0xd4, 0x2f, 0x05, 0x36, 0x2b, 0x4d, 0xc4, 0x44,
	0x3f, 0x28, 0x45, 0xfc, 0x55, 0x65, 0x6b, 0xf7, 0x7e, 0xc1, 0x9d, 0x60, 0x82, 0xfe, 0xe8, 0x90,
	0x95, 0x31, 0xd4, 0xf9, 0x23, 0x59, 0xb0, 0x49, 0x1c, 0x75, 0x3b, 0xf9, 0xc3, 0x7f, 0x6d, 0x72,
	0x24, 0xae, 0x69, 0x77, 0xa4, 0x3f, 0x38, 0x64, 0x69, 0x0c, 0xff, 0x85, 0x08, 0x40, 0x23, 0x5b,
	0xb4, 0xa1, 0x3d, 0xed, 0x76, 0xf2, 0x5f, 0xfd, 0x07, 0xa1, 0x99, 0x78, 0xee, 0x6d, 0xed, 0x15,
	0xdc, 0xc9, 0x77, 0xa4, 0xe9, 0xd8, 0x80, 0x0e, 0x44, 0x08, 0x35, 0xf1, 0x1a, 0x18, 0x33, 0xb3,
	0x55, 0xdd, 0xee, 0x76, 0xf2, 0xe5, 0x31, 0x86, 0xec, 0xb3, 0x78, 0x34, 0x36, 0xfa, 0xf1, 0x31,
	0xbc, 0xed, 0x4b, 0x7f, 0x71, 0x48, 0x7e, 0x84, 0x3f, 0xe2, 0x22, 0x46, 0x88, 0x0d, 0x68, 0x26,
	0x68, 0xe9, 0xff, 0x9c, 0xa0, 0x8b, 0xdc, 0xd0, 0x3a, 0x59, 0xf5, 0x85, 0xf6, 0x64, 0x0b, 0x54,
	0x7b, 0x9f, 0x27, 0xbc, 0x21, 0x42, 0x81, 0x02, 0x74, 0x55, 0x60, 0xc4, 0xf5, 0x0b, 0xb6, 0x6c,
	0x93, 0x5a, 0xe9, 0x76, 0xf2, 0x8b, 0x7d, 0xb7, 0xfd, 0xd9, 0xb8, 0xb7, 0x53, 0x70, 0xa7, 0x36,
	0xa0, 0x48, 0xd8, 0xd0, 0xce, 0x76, 0xc0, 0xc3, 0xb0, 0xc1, 0xbd, 0x17, 0x26, 0x8a, 0x15, 0x1b,
	0xc5, 0x5e, 0xb7, 0x93, 0xdf, 0x19, 0xf7, 0xc6, 0xf6, 0xd7, 0x16, 0x4b, 0x3c, 0x5f, 0xde, 0xc0,
	0xea, 0x26, 0x76, 0xa6, 0x55, 0xb2, 0x2a, 0x3c, 0xff, 0x99, 0x06, 0xf5, 0xd0, 0x43, 0xd1, 0x02,
	0xb3, 0x9f, 0x1e, 0x2b, 0x11, 0x04, 0xa0, 0xec, 0x66, 0xbe, 0x6a, 0x37, 0x97, 0xa9, 0x1a, 0xf3,
	0x5d, 0x98, 0xc4, 0x0f, 0x6e, 0xdf, 0x1f, 0xd9, 0xcd, 0xf1, 0x32, 0x52, 0xba, 0x43, 0xee, 0x9c,
	0x70, 0x0f, 0xa5, 0x6a, 0xbb, 0xa0, 0x01, 0xfb, 0xdf, 0x96, 0x9c, 0xb5, 0x33, 0x9e, 0x34, 0x6b,
	0x19, 0x21, 0x06, 0x0d, 0xe4, 0xad, 0x81, 0xa9, 0x9a, 0xea, 0x77, 0xbf, 0x9f, 0xe6, 0x9c, 0x37,
	0xa7, 0x39, 0xe7, 0xaf, 0xd3, 0x9c, 0xf3, 0xd3, 0x59, 0xee, 0xca, 0x9b, 0xb3, 0xdc, 0x95, 0x3f,
	0xcf, 0x72, 0x57, 0x9e, 0x1f, 0x04, 0x02, 0x9b, 0x69, 0x63, 0xc3, 0x93, 0x51, 0x39, 0x3b, 0x47,
	0xad, 0x8f, 0x3b, 0x86, 0xad, 0xf7, 0x4f, 0x52, 0xeb, 0xbd, 0x83, 0xd8, 0xab, 0xde, 0x51, 0x0c,
	0xdb, 0x09, 0xe8, 0xc6, 0xac, 0x3d, 0x28, 0x6d, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x70,
	0x84, 0x3a, 0xcb, 0x09, 0x00, 0x00,
}

func (m *Model) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Model) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Model) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FactoryResetStepsInstruction) > 0 {
		i -= len(m.FactoryResetStepsInstruction)
		copy(dAtA[i:], m.FactoryResetStepsInstruction)
		i = encodeVarintModel(dAtA, i, uint64(len(m.FactoryResetStepsInstruction)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xfa
	}
	if m.FactoryResetStepsHint != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.FactoryResetStepsHint))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf0
	}
	if len(m.IcdUserActiveModeTriggerInstruction) > 0 {
		i -= len(m.IcdUserActiveModeTriggerInstruction)
		copy(dAtA[i:], m.IcdUserActiveModeTriggerInstruction)
		i = encodeVarintModel(dAtA, i, uint64(len(m.IcdUserActiveModeTriggerInstruction)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xea
	}
	if m.IcdUserActiveModeTriggerHint != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.IcdUserActiveModeTriggerHint))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe0
	}
	if len(m.CommissioningFallbackUrl) > 0 {
		i -= len(m.CommissioningFallbackUrl)
		copy(dAtA[i:], m.CommissioningFallbackUrl)
		i = encodeVarintModel(dAtA, i, uint64(len(m.CommissioningFallbackUrl)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xda
	}
	if m.DiscoveryCapabilitiesBitmask != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.DiscoveryCapabilitiesBitmask))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if len(m.EnhancedSetupFlowMaintenanceUrl) > 0 {
		i -= len(m.EnhancedSetupFlowMaintenanceUrl)
		copy(dAtA[i:], m.EnhancedSetupFlowMaintenanceUrl)
		i = encodeVarintModel(dAtA, i, uint64(len(m.EnhancedSetupFlowMaintenanceUrl)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if m.EnhancedSetupFlowTCFileSize != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.EnhancedSetupFlowTCFileSize))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	if len(m.EnhancedSetupFlowTCDigest) > 0 {
		i -= len(m.EnhancedSetupFlowTCDigest)
		copy(dAtA[i:], m.EnhancedSetupFlowTCDigest)
		i = encodeVarintModel(dAtA, i, uint64(len(m.EnhancedSetupFlowTCDigest)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if m.EnhancedSetupFlowTCRevision != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.EnhancedSetupFlowTCRevision))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if len(m.EnhancedSetupFlowTCUrl) > 0 {
		i -= len(m.EnhancedSetupFlowTCUrl)
		copy(dAtA[i:], m.EnhancedSetupFlowTCUrl)
		i = encodeVarintModel(dAtA, i, uint64(len(m.EnhancedSetupFlowTCUrl)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if m.EnhancedSetupFlowOptions != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.EnhancedSetupFlowOptions))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.SchemaVersion != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.SchemaVersion))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintModel(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.LsfRevision != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.LsfRevision))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.LsfUrl) > 0 {
		i -= len(m.LsfUrl)
		copy(dAtA[i:], m.LsfUrl)
		i = encodeVarintModel(dAtA, i, uint64(len(m.LsfUrl)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.ProductUrl) > 0 {
		i -= len(m.ProductUrl)
		copy(dAtA[i:], m.ProductUrl)
		i = encodeVarintModel(dAtA, i, uint64(len(m.ProductUrl)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.SupportUrl) > 0 {
		i -= len(m.SupportUrl)
		copy(dAtA[i:], m.SupportUrl)
		i = encodeVarintModel(dAtA, i, uint64(len(m.SupportUrl)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.UserManualUrl) > 0 {
		i -= len(m.UserManualUrl)
		copy(dAtA[i:], m.UserManualUrl)
		i = encodeVarintModel(dAtA, i, uint64(len(m.UserManualUrl)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.CommissioningModeSecondaryStepsInstruction) > 0 {
		i -= len(m.CommissioningModeSecondaryStepsInstruction)
		copy(dAtA[i:], m.CommissioningModeSecondaryStepsInstruction)
		i = encodeVarintModel(dAtA, i, uint64(len(m.CommissioningModeSecondaryStepsInstruction)))
		i--
		dAtA[i] = 0x62
	}
	if m.CommissioningModeSecondaryStepsHint != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.CommissioningModeSecondaryStepsHint))
		i--
		dAtA[i] = 0x58
	}
	if len(m.CommissioningModeInitialStepsInstruction) > 0 {
		i -= len(m.CommissioningModeInitialStepsInstruction)
		copy(dAtA[i:], m.CommissioningModeInitialStepsInstruction)
		i = encodeVarintModel(dAtA, i, uint64(len(m.CommissioningModeInitialStepsInstruction)))
		i--
		dAtA[i] = 0x52
	}
	if m.CommissioningModeInitialStepsHint != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.CommissioningModeInitialStepsHint))
		i--
		dAtA[i] = 0x48
	}
	if len(m.CommissioningCustomFlowUrl) > 0 {
		i -= len(m.CommissioningCustomFlowUrl)
		copy(dAtA[i:], m.CommissioningCustomFlowUrl)
		i = encodeVarintModel(dAtA, i, uint64(len(m.CommissioningCustomFlowUrl)))
		i--
		dAtA[i] = 0x42
	}
	if m.CommissioningCustomFlow != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.CommissioningCustomFlow))
		i--
		dAtA[i] = 0x38
	}
	if len(m.PartNumber) > 0 {
		i -= len(m.PartNumber)
		copy(dAtA[i:], m.PartNumber)
		i = encodeVarintModel(dAtA, i, uint64(len(m.PartNumber)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ProductLabel) > 0 {
		i -= len(m.ProductLabel)
		copy(dAtA[i:], m.ProductLabel)
		i = encodeVarintModel(dAtA, i, uint64(len(m.ProductLabel)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ProductName) > 0 {
		i -= len(m.ProductName)
		copy(dAtA[i:], m.ProductName)
		i = encodeVarintModel(dAtA, i, uint64(len(m.ProductName)))
		i--
		dAtA[i] = 0x22
	}
	if m.DeviceTypeId != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.DeviceTypeId))
		i--
		dAtA[i] = 0x18
	}
	if m.Pid != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Pid))
		i--
		dAtA[i] = 0x10
	}
	if m.Vid != 0 {
		i = encodeVarintModel(dAtA, i, uint64(m.Vid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintModel(dAtA []byte, offset int, v uint64) int {
	offset -= sovModel(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Model) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vid != 0 {
		n += 1 + sovModel(uint64(m.Vid))
	}
	if m.Pid != 0 {
		n += 1 + sovModel(uint64(m.Pid))
	}
	if m.DeviceTypeId != 0 {
		n += 1 + sovModel(uint64(m.DeviceTypeId))
	}
	l = len(m.ProductName)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.ProductLabel)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.PartNumber)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.CommissioningCustomFlow != 0 {
		n += 1 + sovModel(uint64(m.CommissioningCustomFlow))
	}
	l = len(m.CommissioningCustomFlowUrl)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.CommissioningModeInitialStepsHint != 0 {
		n += 1 + sovModel(uint64(m.CommissioningModeInitialStepsHint))
	}
	l = len(m.CommissioningModeInitialStepsInstruction)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	if m.CommissioningModeSecondaryStepsHint != 0 {
		n += 1 + sovModel(uint64(m.CommissioningModeSecondaryStepsHint))
	}
	l = len(m.CommissioningModeSecondaryStepsInstruction)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.UserManualUrl)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.SupportUrl)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.ProductUrl)
	if l > 0 {
		n += 1 + l + sovModel(uint64(l))
	}
	l = len(m.LsfUrl)
	if l > 0 {
		n += 2 + l + sovModel(uint64(l))
	}
	if m.LsfRevision != 0 {
		n += 2 + sovModel(uint64(m.LsfRevision))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 2 + l + sovModel(uint64(l))
	}
	if m.SchemaVersion != 0 {
		n += 2 + sovModel(uint64(m.SchemaVersion))
	}
	if m.EnhancedSetupFlowOptions != 0 {
		n += 2 + sovModel(uint64(m.EnhancedSetupFlowOptions))
	}
	l = len(m.EnhancedSetupFlowTCUrl)
	if l > 0 {
		n += 2 + l + sovModel(uint64(l))
	}
	if m.EnhancedSetupFlowTCRevision != 0 {
		n += 2 + sovModel(uint64(m.EnhancedSetupFlowTCRevision))
	}
	l = len(m.EnhancedSetupFlowTCDigest)
	if l > 0 {
		n += 2 + l + sovModel(uint64(l))
	}
	if m.EnhancedSetupFlowTCFileSize != 0 {
		n += 2 + sovModel(uint64(m.EnhancedSetupFlowTCFileSize))
	}
	l = len(m.EnhancedSetupFlowMaintenanceUrl)
	if l > 0 {
		n += 2 + l + sovModel(uint64(l))
	}
	if m.DiscoveryCapabilitiesBitmask != 0 {
		n += 2 + sovModel(uint64(m.DiscoveryCapabilitiesBitmask))
	}
	l = len(m.CommissioningFallbackUrl)
	if l > 0 {
		n += 2 + l + sovModel(uint64(l))
	}
	if m.IcdUserActiveModeTriggerHint != 0 {
		n += 2 + sovModel(uint64(m.IcdUserActiveModeTriggerHint))
	}
	l = len(m.IcdUserActiveModeTriggerInstruction)
	if l > 0 {
		n += 2 + l + sovModel(uint64(l))
	}
	if m.FactoryResetStepsHint != 0 {
		n += 2 + sovModel(uint64(m.FactoryResetStepsHint))
	}
	l = len(m.FactoryResetStepsInstruction)
	if l > 0 {
		n += 2 + l + sovModel(uint64(l))
	}
	return n
}

func sovModel(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozModel(x uint64) (n int) {
	return sovModel(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Model) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Model: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Model: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vid", wireType)
			}
			m.Vid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Vid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			m.Pid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceTypeId", wireType)
			}
			m.DeviceTypeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeviceTypeId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductLabel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductLabel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PartNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissioningCustomFlow", wireType)
			}
			m.CommissioningCustomFlow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommissioningCustomFlow |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissioningCustomFlowUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommissioningCustomFlowUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissioningModeInitialStepsHint", wireType)
			}
			m.CommissioningModeInitialStepsHint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommissioningModeInitialStepsHint |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissioningModeInitialStepsInstruction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommissioningModeInitialStepsInstruction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissioningModeSecondaryStepsHint", wireType)
			}
			m.CommissioningModeSecondaryStepsHint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommissioningModeSecondaryStepsHint |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissioningModeSecondaryStepsInstruction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommissioningModeSecondaryStepsInstruction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserManualUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserManualUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LsfUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LsfUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LsfRevision", wireType)
			}
			m.LsfRevision = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LsfRevision |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaVersion", wireType)
			}
			m.SchemaVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SchemaVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnhancedSetupFlowOptions", wireType)
			}
			m.EnhancedSetupFlowOptions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnhancedSetupFlowOptions |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnhancedSetupFlowTCUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnhancedSetupFlowTCUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnhancedSetupFlowTCRevision", wireType)
			}
			m.EnhancedSetupFlowTCRevision = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnhancedSetupFlowTCRevision |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnhancedSetupFlowTCDigest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnhancedSetupFlowTCDigest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnhancedSetupFlowTCFileSize", wireType)
			}
			m.EnhancedSetupFlowTCFileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnhancedSetupFlowTCFileSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnhancedSetupFlowMaintenanceUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnhancedSetupFlowMaintenanceUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiscoveryCapabilitiesBitmask", wireType)
			}
			m.DiscoveryCapabilitiesBitmask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiscoveryCapabilitiesBitmask |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 27:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommissioningFallbackUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommissioningFallbackUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 28:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IcdUserActiveModeTriggerHint", wireType)
			}
			m.IcdUserActiveModeTriggerHint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IcdUserActiveModeTriggerHint |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 29:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IcdUserActiveModeTriggerInstruction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IcdUserActiveModeTriggerInstruction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactoryResetStepsHint", wireType)
			}
			m.FactoryResetStepsHint = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FactoryResetStepsHint |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 31:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactoryResetStepsInstruction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FactoryResetStepsInstruction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipModel(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowModel
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthModel
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupModel
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthModel
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthModel        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowModel          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupModel = fmt.Errorf("proto: unexpected end of group")
)
